name: Run autopep8

on:
    push:
        branches: ["main", "fall_2024"]
    pull_request:
        branches: ["main", "fall_2024"]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12.6"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

                  # Checks if requirements.txt already exists, then creates it if it doesn't
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    autopep8:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Execute AutoPep8
              run: |
                  pip install autopep8
                  autopep8 --in-place -r .
