name: Get coverage report

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: write

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.6
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              continue-on-error: true
              run: |
                  coverage run -m pytest
                  coverage report -m

            - name: Upload coverage report
              if: success() || failure()
              uses: coverallsapp/github-action@v2.3.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  format: python
                  allow-empty: true
